# Generated by Django 4.2.13 on 2024-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project_alter_contactusmodel_email_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ContactAdmin',
        ),
        migrations.DeleteModel(
            name='ContactUsModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
