# Generated by Django 4.2.13 on 2024-07-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_communitymessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitymessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
