# Generated by Django 4.2.13 on 2024-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_created_at_communitymessage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community_images/'),
        ),
    ]
