# Generated by Django 4.2.13 on 2024-08-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_communitymessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/contact_images/'),
        ),
    ]
