pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'django:latest'
                    // Set the working directory for Django project
                    args '-w /var/jenkins_home/workspace/Team-28/TeachSmart/your-django-project-directory'
                }
            }

        }
        stage('Test') {
            agent {
                docker {
                    image 'django:latest'
                    // Set the working directory for Django project
                    args '-w /var/jenkins_home/workspace/Team-28/TeachSmart/your-django-project-directory'
                }
            }
            steps {
                // Run tests
                sh 'python manage.py test --verbosity=2 --junit-xml=test-reports/results.xml'
            }
            post {
                always {
                    // Publish test results
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
